hardware:

# =============================================================================
# CAMERAS VARIABLES
# =============================================================================
  cameras:
    camera1: 
      src: 0
      name: "Left Camera"
      resolution: [640, 480]
      enable: true
    camera2:
      src: 1
      name: "Right Camera"
      resolution: [640, 480]
      enable: true
    treshold:
      value: 5000 # This value is temporal, once we have installed the "poste", we'll find the right value
  
# =============================================================================
# AUDIO VARIABLES
# =============================================================================

  audio:
    volume: 80
